FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install && npm install -g serve
RUN npm install -g dotenv
COPY . .
RUN ls -a


# ARG REACT_APP_FIREBASE_API_KEY=process.env.REACT_APP_FIREBASE_API_KEY
# ARG REACT_APP_FIREBASE_AUTH_DOMAIN=process.env.REACT_APP_FIREBASE_AUTH_DOMAIN
# ARG REACT_APP_FIREBASE_DATABASE_URL=process.env.REACT_APP_FIREBASE_DATABASE_URL
# ARG REACT_APP_FIREBASE_PROJECT_ID=process.env.REACT_APP_FIREBASE_PROJECT_ID-way
# ARG REACT_APP_FIREBASE_STORAGE_BUCKET=process.env.REACT_APP_FIREBASE_STORAGE_BUCKET
# ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID=process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID 
# ARG REACT_APP_FIREBASE_APP_ID=process.env.REACT_APP_FIREBASE_APP_ID
# ARG REACT_APP_FIREBASE_MEASUREMENT_ID=process.env.REACT_APP_FIREBASE_MEASUREMENT_ID
RUN npm run build

EXPOSE 80

# CMD ["serve","-l","80", "-s", "build"]
CMD ["npm", "start"]